version: '2'
services:

  development:
    build:
      context: .
      dockerfile: tests/Dockerfile.dev
    volumes:
      - ./src:/package/src
      - ./.babelrc:/package/.babelrc
      - ./package.json:/package/package.json

  distribution:
    build:
      context: .
      dockerfile: tests/Dockerfile.dev
    command: ["npm", "run", "i:transpile"]
    volumes:
      - "./src:/package/src"
      - "./lib:/package/lib"
      - "./package.json:/package/package.json"
      - "./.babelrc:/package/.babelrc"
