const CLIENT = 'MC'
const WORKER = 'MW'
const MINISTER = 'MM'
const MINISTER_NOTIFIER = 'MMN'

const C_HELLO = '1'
const C_HEARTBEAT = '2'
const C_DISCONNECT = '3'
const C_REQUEST = '4'

const W_READY = '1'
const W_HEARTBEAT = '2'
const W_DISCONNECT = '3'
const W_PARTIAL_RESPONSE = '4'
const W_FINAL_RESPONSE = '5'
const W_ERROR_RESPONSE = '6'

const M_HELLO = '1'
const M_WORKERS_AVAILABILITY = '2'
const M_DISCONNECT = '3'
const M_WORKERS_UPDATE_INTERVAL = 1000

const MN_NEW_MINISTER_CONNECTED = '1'

const HEARTBEAT_LIVENESS = 3
const HEARTBEAT_CHECK_INTERVAL = 1000

const RESPONSE_TIMEOUT = 'RTO'

const MINISTERS = {
  CLIENT,
  WORKER,
  MINISTER,
  MINISTER_NOTIFIER,

  C_HELLO,
  C_HEARTBEAT,
  C_DISCONNECT,
  C_REQUEST,

  W_READY,
  W_HEARTBEAT,
  W_DISCONNECT,
  W_PARTIAL_RESPONSE,
  W_FINAL_RESPONSE,
  W_ERROR_RESPONSE,

  M_HELLO,
  M_WORKERS_AVAILABILITY,
  M_DISCONNECT,
  M_WORKERS_UPDATE_INTERVAL,

  MN_NEW_MINISTER_CONNECTED,

  HEARTBEAT_LIVENESS,
  HEARTBEAT_CHECK_INTERVAL,

  RESPONSE_TIMEOUT
}

export default MINISTERS
